version: "3.3"
services: 
   jenkins:
        container_name: jenkins
        image: jenkins-ansible
        build:
           context: jenkins-ansible
        ports: 
         - "8080:8080"
        volumes: 
          - "$PWD/jenkins_home:/var/jenkins_home"
        networks:
           - jenkins
   centos-ssh:
        container_name: centos-ssh
        image: centos-ssh
        build:
           context: centos
        networks: 
          - jenkins
        volumes:
         - "$PWD/db_backup.sh:/tmp/db_backup.sh"  
   database:
       container_name: db
       image: mysql:5.7
       environment:
           - "MYSQL_ROOT_PASSWORD=redhat"
       volumes:
          -   "$PWD/db_data:/var/lib/mysql"
       networks:
           - jenkins 
networks:
   jenkins:


