version: "3.3"
services: 
   jenkins:
        container_name: jenkins
        image: jenkins-ansible
        deploy:
         restart_policy:
           condition: on-failure
        build:
           context: jenkins-ansible
        ports: 
         - "8080:8080"
        volumes: 
          - "$PWD/jenkins_home:/var/jenkins_home"
        networks:
           - jenkins
   centos-ssh:
        container_name: centos-ssh
        image: centos-ssh
        deploy:
         restart_policy:
           condition: on-failure
        build:
           context: centos
        networks: 
          - jenkins
        volumes:
         - "$PWD/db_backup.sh:/tmp/db_backup.sh"
   web:
      container_name: web
      image: ansible-web 
      deploy:
         restart_policy:
           condition: on-failure
      build:
          context: jenkins-ansible/web/
      networks:
         - jenkins
      ports:
         - "80:80"
                  
   database:
       container_name: db
       image: mysql:5.7
       deploy:
         restart_policy:
           condition: on-failure
       environment:
           - "MYSQL_ROOT_PASSWORD=redhat"
       volumes:
          -   "$PWD/db_data:/var/lib/mysql"
       networks:
           - jenkins 
#######
   git:
      container_name: git_server
      image: 'gitlab/gitlab-ee:latest'
      restart: always
      hostname: 'gitlab.example.com'
      # environment:
      # GITLAB_OMNIBUS_CONFIG: |
      #    external_url 'https://gitlab.example.com'
      #    # Add any other gitlab.rb configuration here, each on its own line
      ports:
      - '8089:80'
      - '443:443'
      - '2022:22'
      volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
      networks:
         - jenkins
networks:
   jenkins:


