version: "3.3"
services: 
   jenkins:
        container_name: jenkins
        image: jenkins-ansible
<<<<<<< HEAD
        deploy:
         restart_policy:
           condition: on-failure
=======
>>>>>>> bdb1c09f8b4d754a2d4f81abb1307af26d0add7d
        build:
           context: jenkins-ansible
        ports: 
         - "8080:8080"
        volumes: 
          - "$PWD/jenkins_home:/var/jenkins_home"
        networks:
           - jenkins
   centos-ssh:
        container_name: centos-ssh
        image: centos-ssh
        deploy:
         restart_policy:
           condition: on-failure
        build:
           context: centos
        networks: 
          - jenkins
        volumes:
         - "$PWD/db_backup.sh:/tmp/db_backup.sh"
   web:
      container_name: web
      image: ansible-web 
<<<<<<< HEAD
      deploy:
         restart_policy:
           condition: on-failure
=======
>>>>>>> bdb1c09f8b4d754a2d4f81abb1307af26d0add7d
      build:
          context: jenkins-ansible/web/
      networks:
         - jenkins
      ports:
         - "80:80"
                  
   database:
       container_name: db
       image: mysql:5.7
       deploy:
         restart_policy:
           condition: on-failure
       environment:
           - "MYSQL_ROOT_PASSWORD=redhat"
       volumes:
          -   "$PWD/db_data:/var/lib/mysql"
       networks:
           - jenkins 
networks:
   jenkins:


